spring:
  application:
    name: tictactoe
  datasource:
    url: jdbc:postgresql://localhost:5432/tictactoe
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
  liquiBase:
    change-log: db/changelog/main-changelog.xml
    enabled: false
jwt:
  key: vFHK5QhGyU1TkVhslB7fykl9mB4Hfr+N3dQ5BhvZ2K8=
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
